class Caboose::FormSubmission < ActiveRecord::Base

	self.table_name = "form_submissions"

	belongs_to :site, :class_name => 'Caboose::Site'     

  attr_accessible :id,
  	:site_id,
  	:block_id,
  	:form_name,
  	:sent_to,
  	:bcc_to,
  	:category,
    :recaptcha_score,
  	:date_submitted,
    :ip_address,
  	:is_spam,
  	:is_deleted,
  	:field1_name,
  	:field1_description,
  	:field1_value,
  	:field2_name,
  	:field2_description,
  	:field2_value,
  	:field3_name,
  	:field3_description,
  	:field3_value,
  	:field4_name,
  	:field4_description,
  	:field4_value,
  	:field5_name,
  	:field5_description,
  	:field5_value,
  	:field6_name,
  	:field6_description,
  	:field6_value,
  	:field7_name,
  	:field7_description,
  	:field7_value,
  	:field8_name,
  	:field8_description,
  	:field8_value,
  	:field9_name,
  	:field9_description,
  	:field9_value,
  	:field10_name,
  	:field10_description,
  	:field10_value,
  	:field11_name,
  	:field11_description,
  	:field11_value,
  	:field12_name,
  	:field12_description,
  	:field12_value,
  	:field13_name,
  	:field13_description,
  	:field13_value,
  	:field14_name,
  	:field14_description,
  	:field14_value,
  	:field15_name,
  	:field15_description,
  	:field15_value,
  	:field16_name,
  	:field16_description,
  	:field16_value,
  	:field17_name,
  	:field17_description,
  	:field17_value,
  	:field18_name,
  	:field18_description,
  	:field18_value,
  	:field19_name,
  	:field19_description,
  	:field19_value,
  	:field20_name,
  	:field20_description,
  	:field20_value

end